// Code generated by ent, DO NOT EDIT.

package paymentrefund

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentrefund type in the database.
	Label = "payment_refund"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldRefundNo holds the string denoting the refund_no field in the database.
	FieldRefundNo = "refund_no"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldGatewayAmount holds the string denoting the gateway_amount field in the database.
	FieldGatewayAmount = "gateway_amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProviderRefundID holds the string denoting the provider_refund_id field in the database.
	FieldProviderRefundID = "provider_refund_id"
	// FieldOperator holds the string denoting the operator field in the database.
	FieldOperator = "operator"
	// FieldDeductionType holds the string denoting the deduction_type field in the database.
	FieldDeductionType = "deduction_type"
	// FieldBalanceDeducted holds the string denoting the balance_deducted field in the database.
	FieldBalanceDeducted = "balance_deducted"
	// FieldSubDaysDeducted holds the string denoting the sub_days_deducted field in the database.
	FieldSubDaysDeducted = "sub_days_deducted"
	// FieldDeductionRollbackOk holds the string denoting the deduction_rollback_ok field in the database.
	FieldDeductionRollbackOk = "deduction_rollback_ok"
	// FieldForce holds the string denoting the force field in the database.
	FieldForce = "force"
	// FieldFailureReason holds the string denoting the failure_reason field in the database.
	FieldFailureReason = "failure_reason"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the paymentrefund in the database.
	Table = "payment_refunds"
)

// Columns holds all SQL columns for paymentrefund fields.
var Columns = []string{
	FieldID,
	FieldOrderID,
	FieldRefundNo,
	FieldAmount,
	FieldGatewayAmount,
	FieldCurrency,
	FieldReason,
	FieldStatus,
	FieldProviderRefundID,
	FieldOperator,
	FieldDeductionType,
	FieldBalanceDeducted,
	FieldSubDaysDeducted,
	FieldDeductionRollbackOk,
	FieldForce,
	FieldFailureReason,
	FieldCompletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RefundNoValidator is a validator for the "refund_no" field. It is called by the builders before save.
	RefundNoValidator func(string) error
	// DefaultGatewayAmount holds the default value on creation for the "gateway_amount" field.
	DefaultGatewayAmount float64
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultProviderRefundID holds the default value on creation for the "provider_refund_id" field.
	DefaultProviderRefundID string
	// ProviderRefundIDValidator is a validator for the "provider_refund_id" field. It is called by the builders before save.
	ProviderRefundIDValidator func(string) error
	// DefaultOperator holds the default value on creation for the "operator" field.
	DefaultOperator string
	// OperatorValidator is a validator for the "operator" field. It is called by the builders before save.
	OperatorValidator func(string) error
	// DefaultDeductionType holds the default value on creation for the "deduction_type" field.
	DefaultDeductionType string
	// DeductionTypeValidator is a validator for the "deduction_type" field. It is called by the builders before save.
	DeductionTypeValidator func(string) error
	// DefaultBalanceDeducted holds the default value on creation for the "balance_deducted" field.
	DefaultBalanceDeducted float64
	// DefaultSubDaysDeducted holds the default value on creation for the "sub_days_deducted" field.
	DefaultSubDaysDeducted int
	// DefaultDeductionRollbackOk holds the default value on creation for the "deduction_rollback_ok" field.
	DefaultDeductionRollbackOk bool
	// DefaultForce holds the default value on creation for the "force" field.
	DefaultForce bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentRefund queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByRefundNo orders the results by the refund_no field.
func ByRefundNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundNo, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByGatewayAmount orders the results by the gateway_amount field.
func ByGatewayAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGatewayAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProviderRefundID orders the results by the provider_refund_id field.
func ByProviderRefundID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderRefundID, opts...).ToFunc()
}

// ByOperator orders the results by the operator field.
func ByOperator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperator, opts...).ToFunc()
}

// ByDeductionType orders the results by the deduction_type field.
func ByDeductionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeductionType, opts...).ToFunc()
}

// ByBalanceDeducted orders the results by the balance_deducted field.
func ByBalanceDeducted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceDeducted, opts...).ToFunc()
}

// BySubDaysDeducted orders the results by the sub_days_deducted field.
func BySubDaysDeducted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubDaysDeducted, opts...).ToFunc()
}

// ByDeductionRollbackOk orders the results by the deduction_rollback_ok field.
func ByDeductionRollbackOk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeductionRollbackOk, opts...).ToFunc()
}

// ByForce orders the results by the force field.
func ByForce(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForce, opts...).ToFunc()
}

// ByFailureReason orders the results by the failure_reason field.
func ByFailureReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureReason, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
