// Code generated by ent, DO NOT EDIT.

package paymentrefund

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldID, id))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldOrderID, v))
}

// RefundNo applies equality check predicate on the "refund_no" field. It's identical to RefundNoEQ.
func RefundNo(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldRefundNo, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldAmount, v))
}

// GatewayAmount applies equality check predicate on the "gateway_amount" field. It's identical to GatewayAmountEQ.
func GatewayAmount(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldGatewayAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldCurrency, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldReason, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldStatus, v))
}

// ProviderRefundID applies equality check predicate on the "provider_refund_id" field. It's identical to ProviderRefundIDEQ.
func ProviderRefundID(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldProviderRefundID, v))
}

// Operator applies equality check predicate on the "operator" field. It's identical to OperatorEQ.
func Operator(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldOperator, v))
}

// DeductionType applies equality check predicate on the "deduction_type" field. It's identical to DeductionTypeEQ.
func DeductionType(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldDeductionType, v))
}

// BalanceDeducted applies equality check predicate on the "balance_deducted" field. It's identical to BalanceDeductedEQ.
func BalanceDeducted(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldBalanceDeducted, v))
}

// SubDaysDeducted applies equality check predicate on the "sub_days_deducted" field. It's identical to SubDaysDeductedEQ.
func SubDaysDeducted(v int) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldSubDaysDeducted, v))
}

// DeductionRollbackOk applies equality check predicate on the "deduction_rollback_ok" field. It's identical to DeductionRollbackOkEQ.
func DeductionRollbackOk(v bool) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldDeductionRollbackOk, v))
}

// Force applies equality check predicate on the "force" field. It's identical to ForceEQ.
func Force(v bool) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldForce, v))
}

// FailureReason applies equality check predicate on the "failure_reason" field. It's identical to FailureReasonEQ.
func FailureReason(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldFailureReason, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldOrderID, v))
}

// RefundNoEQ applies the EQ predicate on the "refund_no" field.
func RefundNoEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldRefundNo, v))
}

// RefundNoNEQ applies the NEQ predicate on the "refund_no" field.
func RefundNoNEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldRefundNo, v))
}

// RefundNoIn applies the In predicate on the "refund_no" field.
func RefundNoIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldRefundNo, vs...))
}

// RefundNoNotIn applies the NotIn predicate on the "refund_no" field.
func RefundNoNotIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldRefundNo, vs...))
}

// RefundNoGT applies the GT predicate on the "refund_no" field.
func RefundNoGT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldRefundNo, v))
}

// RefundNoGTE applies the GTE predicate on the "refund_no" field.
func RefundNoGTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldRefundNo, v))
}

// RefundNoLT applies the LT predicate on the "refund_no" field.
func RefundNoLT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldRefundNo, v))
}

// RefundNoLTE applies the LTE predicate on the "refund_no" field.
func RefundNoLTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldRefundNo, v))
}

// RefundNoContains applies the Contains predicate on the "refund_no" field.
func RefundNoContains(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContains(FieldRefundNo, v))
}

// RefundNoHasPrefix applies the HasPrefix predicate on the "refund_no" field.
func RefundNoHasPrefix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasPrefix(FieldRefundNo, v))
}

// RefundNoHasSuffix applies the HasSuffix predicate on the "refund_no" field.
func RefundNoHasSuffix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasSuffix(FieldRefundNo, v))
}

// RefundNoEqualFold applies the EqualFold predicate on the "refund_no" field.
func RefundNoEqualFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEqualFold(FieldRefundNo, v))
}

// RefundNoContainsFold applies the ContainsFold predicate on the "refund_no" field.
func RefundNoContainsFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContainsFold(FieldRefundNo, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldAmount, v))
}

// GatewayAmountEQ applies the EQ predicate on the "gateway_amount" field.
func GatewayAmountEQ(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldGatewayAmount, v))
}

// GatewayAmountNEQ applies the NEQ predicate on the "gateway_amount" field.
func GatewayAmountNEQ(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldGatewayAmount, v))
}

// GatewayAmountIn applies the In predicate on the "gateway_amount" field.
func GatewayAmountIn(vs ...float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldGatewayAmount, vs...))
}

// GatewayAmountNotIn applies the NotIn predicate on the "gateway_amount" field.
func GatewayAmountNotIn(vs ...float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldGatewayAmount, vs...))
}

// GatewayAmountGT applies the GT predicate on the "gateway_amount" field.
func GatewayAmountGT(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldGatewayAmount, v))
}

// GatewayAmountGTE applies the GTE predicate on the "gateway_amount" field.
func GatewayAmountGTE(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldGatewayAmount, v))
}

// GatewayAmountLT applies the LT predicate on the "gateway_amount" field.
func GatewayAmountLT(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldGatewayAmount, v))
}

// GatewayAmountLTE applies the LTE predicate on the "gateway_amount" field.
func GatewayAmountLTE(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldGatewayAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContainsFold(FieldCurrency, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContainsFold(FieldReason, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContainsFold(FieldStatus, v))
}

// ProviderRefundIDEQ applies the EQ predicate on the "provider_refund_id" field.
func ProviderRefundIDEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldProviderRefundID, v))
}

// ProviderRefundIDNEQ applies the NEQ predicate on the "provider_refund_id" field.
func ProviderRefundIDNEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldProviderRefundID, v))
}

// ProviderRefundIDIn applies the In predicate on the "provider_refund_id" field.
func ProviderRefundIDIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldProviderRefundID, vs...))
}

// ProviderRefundIDNotIn applies the NotIn predicate on the "provider_refund_id" field.
func ProviderRefundIDNotIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldProviderRefundID, vs...))
}

// ProviderRefundIDGT applies the GT predicate on the "provider_refund_id" field.
func ProviderRefundIDGT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldProviderRefundID, v))
}

// ProviderRefundIDGTE applies the GTE predicate on the "provider_refund_id" field.
func ProviderRefundIDGTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldProviderRefundID, v))
}

// ProviderRefundIDLT applies the LT predicate on the "provider_refund_id" field.
func ProviderRefundIDLT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldProviderRefundID, v))
}

// ProviderRefundIDLTE applies the LTE predicate on the "provider_refund_id" field.
func ProviderRefundIDLTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldProviderRefundID, v))
}

// ProviderRefundIDContains applies the Contains predicate on the "provider_refund_id" field.
func ProviderRefundIDContains(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContains(FieldProviderRefundID, v))
}

// ProviderRefundIDHasPrefix applies the HasPrefix predicate on the "provider_refund_id" field.
func ProviderRefundIDHasPrefix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasPrefix(FieldProviderRefundID, v))
}

// ProviderRefundIDHasSuffix applies the HasSuffix predicate on the "provider_refund_id" field.
func ProviderRefundIDHasSuffix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasSuffix(FieldProviderRefundID, v))
}

// ProviderRefundIDEqualFold applies the EqualFold predicate on the "provider_refund_id" field.
func ProviderRefundIDEqualFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEqualFold(FieldProviderRefundID, v))
}

// ProviderRefundIDContainsFold applies the ContainsFold predicate on the "provider_refund_id" field.
func ProviderRefundIDContainsFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContainsFold(FieldProviderRefundID, v))
}

// OperatorEQ applies the EQ predicate on the "operator" field.
func OperatorEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldOperator, v))
}

// OperatorNEQ applies the NEQ predicate on the "operator" field.
func OperatorNEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldOperator, v))
}

// OperatorIn applies the In predicate on the "operator" field.
func OperatorIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldOperator, vs...))
}

// OperatorNotIn applies the NotIn predicate on the "operator" field.
func OperatorNotIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldOperator, vs...))
}

// OperatorGT applies the GT predicate on the "operator" field.
func OperatorGT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldOperator, v))
}

// OperatorGTE applies the GTE predicate on the "operator" field.
func OperatorGTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldOperator, v))
}

// OperatorLT applies the LT predicate on the "operator" field.
func OperatorLT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldOperator, v))
}

// OperatorLTE applies the LTE predicate on the "operator" field.
func OperatorLTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldOperator, v))
}

// OperatorContains applies the Contains predicate on the "operator" field.
func OperatorContains(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContains(FieldOperator, v))
}

// OperatorHasPrefix applies the HasPrefix predicate on the "operator" field.
func OperatorHasPrefix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasPrefix(FieldOperator, v))
}

// OperatorHasSuffix applies the HasSuffix predicate on the "operator" field.
func OperatorHasSuffix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasSuffix(FieldOperator, v))
}

// OperatorEqualFold applies the EqualFold predicate on the "operator" field.
func OperatorEqualFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEqualFold(FieldOperator, v))
}

// OperatorContainsFold applies the ContainsFold predicate on the "operator" field.
func OperatorContainsFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContainsFold(FieldOperator, v))
}

// DeductionTypeEQ applies the EQ predicate on the "deduction_type" field.
func DeductionTypeEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldDeductionType, v))
}

// DeductionTypeNEQ applies the NEQ predicate on the "deduction_type" field.
func DeductionTypeNEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldDeductionType, v))
}

// DeductionTypeIn applies the In predicate on the "deduction_type" field.
func DeductionTypeIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldDeductionType, vs...))
}

// DeductionTypeNotIn applies the NotIn predicate on the "deduction_type" field.
func DeductionTypeNotIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldDeductionType, vs...))
}

// DeductionTypeGT applies the GT predicate on the "deduction_type" field.
func DeductionTypeGT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldDeductionType, v))
}

// DeductionTypeGTE applies the GTE predicate on the "deduction_type" field.
func DeductionTypeGTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldDeductionType, v))
}

// DeductionTypeLT applies the LT predicate on the "deduction_type" field.
func DeductionTypeLT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldDeductionType, v))
}

// DeductionTypeLTE applies the LTE predicate on the "deduction_type" field.
func DeductionTypeLTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldDeductionType, v))
}

// DeductionTypeContains applies the Contains predicate on the "deduction_type" field.
func DeductionTypeContains(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContains(FieldDeductionType, v))
}

// DeductionTypeHasPrefix applies the HasPrefix predicate on the "deduction_type" field.
func DeductionTypeHasPrefix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasPrefix(FieldDeductionType, v))
}

// DeductionTypeHasSuffix applies the HasSuffix predicate on the "deduction_type" field.
func DeductionTypeHasSuffix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasSuffix(FieldDeductionType, v))
}

// DeductionTypeEqualFold applies the EqualFold predicate on the "deduction_type" field.
func DeductionTypeEqualFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEqualFold(FieldDeductionType, v))
}

// DeductionTypeContainsFold applies the ContainsFold predicate on the "deduction_type" field.
func DeductionTypeContainsFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContainsFold(FieldDeductionType, v))
}

// BalanceDeductedEQ applies the EQ predicate on the "balance_deducted" field.
func BalanceDeductedEQ(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldBalanceDeducted, v))
}

// BalanceDeductedNEQ applies the NEQ predicate on the "balance_deducted" field.
func BalanceDeductedNEQ(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldBalanceDeducted, v))
}

// BalanceDeductedIn applies the In predicate on the "balance_deducted" field.
func BalanceDeductedIn(vs ...float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldBalanceDeducted, vs...))
}

// BalanceDeductedNotIn applies the NotIn predicate on the "balance_deducted" field.
func BalanceDeductedNotIn(vs ...float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldBalanceDeducted, vs...))
}

// BalanceDeductedGT applies the GT predicate on the "balance_deducted" field.
func BalanceDeductedGT(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldBalanceDeducted, v))
}

// BalanceDeductedGTE applies the GTE predicate on the "balance_deducted" field.
func BalanceDeductedGTE(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldBalanceDeducted, v))
}

// BalanceDeductedLT applies the LT predicate on the "balance_deducted" field.
func BalanceDeductedLT(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldBalanceDeducted, v))
}

// BalanceDeductedLTE applies the LTE predicate on the "balance_deducted" field.
func BalanceDeductedLTE(v float64) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldBalanceDeducted, v))
}

// SubDaysDeductedEQ applies the EQ predicate on the "sub_days_deducted" field.
func SubDaysDeductedEQ(v int) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldSubDaysDeducted, v))
}

// SubDaysDeductedNEQ applies the NEQ predicate on the "sub_days_deducted" field.
func SubDaysDeductedNEQ(v int) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldSubDaysDeducted, v))
}

// SubDaysDeductedIn applies the In predicate on the "sub_days_deducted" field.
func SubDaysDeductedIn(vs ...int) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldSubDaysDeducted, vs...))
}

// SubDaysDeductedNotIn applies the NotIn predicate on the "sub_days_deducted" field.
func SubDaysDeductedNotIn(vs ...int) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldSubDaysDeducted, vs...))
}

// SubDaysDeductedGT applies the GT predicate on the "sub_days_deducted" field.
func SubDaysDeductedGT(v int) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldSubDaysDeducted, v))
}

// SubDaysDeductedGTE applies the GTE predicate on the "sub_days_deducted" field.
func SubDaysDeductedGTE(v int) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldSubDaysDeducted, v))
}

// SubDaysDeductedLT applies the LT predicate on the "sub_days_deducted" field.
func SubDaysDeductedLT(v int) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldSubDaysDeducted, v))
}

// SubDaysDeductedLTE applies the LTE predicate on the "sub_days_deducted" field.
func SubDaysDeductedLTE(v int) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldSubDaysDeducted, v))
}

// DeductionRollbackOkEQ applies the EQ predicate on the "deduction_rollback_ok" field.
func DeductionRollbackOkEQ(v bool) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldDeductionRollbackOk, v))
}

// DeductionRollbackOkNEQ applies the NEQ predicate on the "deduction_rollback_ok" field.
func DeductionRollbackOkNEQ(v bool) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldDeductionRollbackOk, v))
}

// ForceEQ applies the EQ predicate on the "force" field.
func ForceEQ(v bool) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldForce, v))
}

// ForceNEQ applies the NEQ predicate on the "force" field.
func ForceNEQ(v bool) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldForce, v))
}

// FailureReasonEQ applies the EQ predicate on the "failure_reason" field.
func FailureReasonEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldFailureReason, v))
}

// FailureReasonNEQ applies the NEQ predicate on the "failure_reason" field.
func FailureReasonNEQ(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldFailureReason, v))
}

// FailureReasonIn applies the In predicate on the "failure_reason" field.
func FailureReasonIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldFailureReason, vs...))
}

// FailureReasonNotIn applies the NotIn predicate on the "failure_reason" field.
func FailureReasonNotIn(vs ...string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldFailureReason, vs...))
}

// FailureReasonGT applies the GT predicate on the "failure_reason" field.
func FailureReasonGT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldFailureReason, v))
}

// FailureReasonGTE applies the GTE predicate on the "failure_reason" field.
func FailureReasonGTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldFailureReason, v))
}

// FailureReasonLT applies the LT predicate on the "failure_reason" field.
func FailureReasonLT(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldFailureReason, v))
}

// FailureReasonLTE applies the LTE predicate on the "failure_reason" field.
func FailureReasonLTE(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldFailureReason, v))
}

// FailureReasonContains applies the Contains predicate on the "failure_reason" field.
func FailureReasonContains(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContains(FieldFailureReason, v))
}

// FailureReasonHasPrefix applies the HasPrefix predicate on the "failure_reason" field.
func FailureReasonHasPrefix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasPrefix(FieldFailureReason, v))
}

// FailureReasonHasSuffix applies the HasSuffix predicate on the "failure_reason" field.
func FailureReasonHasSuffix(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldHasSuffix(FieldFailureReason, v))
}

// FailureReasonIsNil applies the IsNil predicate on the "failure_reason" field.
func FailureReasonIsNil() predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIsNull(FieldFailureReason))
}

// FailureReasonNotNil applies the NotNil predicate on the "failure_reason" field.
func FailureReasonNotNil() predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotNull(FieldFailureReason))
}

// FailureReasonEqualFold applies the EqualFold predicate on the "failure_reason" field.
func FailureReasonEqualFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEqualFold(FieldFailureReason, v))
}

// FailureReasonContainsFold applies the ContainsFold predicate on the "failure_reason" field.
func FailureReasonContainsFold(v string) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldContainsFold(FieldFailureReason, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotNull(FieldCompletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentRefund) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentRefund) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentRefund) predicate.PaymentRefund {
	return predicate.PaymentRefund(sql.NotPredicates(p))
}
