// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentrefund"
)

// PaymentRefund is the model entity for the PaymentRefund schema.
type PaymentRefund struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID int64 `json:"order_id,omitempty"`
	// RefundNo holds the value of the "refund_no" field.
	RefundNo string `json:"refund_no,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// GatewayAmount holds the value of the "gateway_amount" field.
	GatewayAmount float64 `json:"gateway_amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ProviderRefundID holds the value of the "provider_refund_id" field.
	ProviderRefundID string `json:"provider_refund_id,omitempty"`
	// Operator holds the value of the "operator" field.
	Operator string `json:"operator,omitempty"`
	// DeductionType holds the value of the "deduction_type" field.
	DeductionType string `json:"deduction_type,omitempty"`
	// BalanceDeducted holds the value of the "balance_deducted" field.
	BalanceDeducted float64 `json:"balance_deducted,omitempty"`
	// SubDaysDeducted holds the value of the "sub_days_deducted" field.
	SubDaysDeducted int `json:"sub_days_deducted,omitempty"`
	// DeductionRollbackOk holds the value of the "deduction_rollback_ok" field.
	DeductionRollbackOk bool `json:"deduction_rollback_ok,omitempty"`
	// Force holds the value of the "force" field.
	Force bool `json:"force,omitempty"`
	// FailureReason holds the value of the "failure_reason" field.
	FailureReason *string `json:"failure_reason,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentRefund) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentrefund.FieldDeductionRollbackOk, paymentrefund.FieldForce:
			values[i] = new(sql.NullBool)
		case paymentrefund.FieldAmount, paymentrefund.FieldGatewayAmount, paymentrefund.FieldBalanceDeducted:
			values[i] = new(sql.NullFloat64)
		case paymentrefund.FieldID, paymentrefund.FieldOrderID, paymentrefund.FieldSubDaysDeducted:
			values[i] = new(sql.NullInt64)
		case paymentrefund.FieldRefundNo, paymentrefund.FieldCurrency, paymentrefund.FieldReason, paymentrefund.FieldStatus, paymentrefund.FieldProviderRefundID, paymentrefund.FieldOperator, paymentrefund.FieldDeductionType, paymentrefund.FieldFailureReason:
			values[i] = new(sql.NullString)
		case paymentrefund.FieldCompletedAt, paymentrefund.FieldCreatedAt, paymentrefund.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentRefund fields.
func (_m *PaymentRefund) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentrefund.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentrefund.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.Int64
			}
		case paymentrefund.FieldRefundNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_no", values[i])
			} else if value.Valid {
				_m.RefundNo = value.String
			}
		case paymentrefund.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case paymentrefund.FieldGatewayAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_amount", values[i])
			} else if value.Valid {
				_m.GatewayAmount = value.Float64
			}
		case paymentrefund.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case paymentrefund.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case paymentrefund.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case paymentrefund.FieldProviderRefundID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_refund_id", values[i])
			} else if value.Valid {
				_m.ProviderRefundID = value.String
			}
		case paymentrefund.FieldOperator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operator", values[i])
			} else if value.Valid {
				_m.Operator = value.String
			}
		case paymentrefund.FieldDeductionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deduction_type", values[i])
			} else if value.Valid {
				_m.DeductionType = value.String
			}
		case paymentrefund.FieldBalanceDeducted:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_deducted", values[i])
			} else if value.Valid {
				_m.BalanceDeducted = value.Float64
			}
		case paymentrefund.FieldSubDaysDeducted:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sub_days_deducted", values[i])
			} else if value.Valid {
				_m.SubDaysDeducted = int(value.Int64)
			}
		case paymentrefund.FieldDeductionRollbackOk:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field deduction_rollback_ok", values[i])
			} else if value.Valid {
				_m.DeductionRollbackOk = value.Bool
			}
		case paymentrefund.FieldForce:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field force", values[i])
			} else if value.Valid {
				_m.Force = value.Bool
			}
		case paymentrefund.FieldFailureReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_reason", values[i])
			} else if value.Valid {
				_m.FailureReason = new(string)
				*_m.FailureReason = value.String
			}
		case paymentrefund.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case paymentrefund.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentrefund.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentRefund.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentRefund) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentRefund.
// Note that you need to call PaymentRefund.Unwrap() before calling this method if this PaymentRefund
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentRefund) Update() *PaymentRefundUpdateOne {
	return NewPaymentRefundClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentRefund entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentRefund) Unwrap() *PaymentRefund {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentRefund is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentRefund) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentRefund(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("refund_no=")
	builder.WriteString(_m.RefundNo)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("gateway_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.GatewayAmount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("provider_refund_id=")
	builder.WriteString(_m.ProviderRefundID)
	builder.WriteString(", ")
	builder.WriteString("operator=")
	builder.WriteString(_m.Operator)
	builder.WriteString(", ")
	builder.WriteString("deduction_type=")
	builder.WriteString(_m.DeductionType)
	builder.WriteString(", ")
	builder.WriteString("balance_deducted=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceDeducted))
	builder.WriteString(", ")
	builder.WriteString("sub_days_deducted=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubDaysDeducted))
	builder.WriteString(", ")
	builder.WriteString("deduction_rollback_ok=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeductionRollbackOk))
	builder.WriteString(", ")
	builder.WriteString("force=")
	builder.WriteString(fmt.Sprintf("%v", _m.Force))
	builder.WriteString(", ")
	if v := _m.FailureReason; v != nil {
		builder.WriteString("failure_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentRefunds is a parsable slice of PaymentRefund.
type PaymentRefunds []*PaymentRefund
