// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentrefund"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentRefundUpdate is the builder for updating PaymentRefund entities.
type PaymentRefundUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentRefundMutation
}

// Where appends a list predicates to the PaymentRefundUpdate builder.
func (_u *PaymentRefundUpdate) Where(ps ...predicate.PaymentRefund) *PaymentRefundUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *PaymentRefundUpdate) SetOrderID(v int64) *PaymentRefundUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableOrderID(v *int64) *PaymentRefundUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *PaymentRefundUpdate) AddOrderID(v int64) *PaymentRefundUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetRefundNo sets the "refund_no" field.
func (_u *PaymentRefundUpdate) SetRefundNo(v string) *PaymentRefundUpdate {
	_u.mutation.SetRefundNo(v)
	return _u
}

// SetNillableRefundNo sets the "refund_no" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableRefundNo(v *string) *PaymentRefundUpdate {
	if v != nil {
		_u.SetRefundNo(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentRefundUpdate) SetAmount(v float64) *PaymentRefundUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableAmount(v *float64) *PaymentRefundUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentRefundUpdate) AddAmount(v float64) *PaymentRefundUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetGatewayAmount sets the "gateway_amount" field.
func (_u *PaymentRefundUpdate) SetGatewayAmount(v float64) *PaymentRefundUpdate {
	_u.mutation.ResetGatewayAmount()
	_u.mutation.SetGatewayAmount(v)
	return _u
}

// SetNillableGatewayAmount sets the "gateway_amount" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableGatewayAmount(v *float64) *PaymentRefundUpdate {
	if v != nil {
		_u.SetGatewayAmount(*v)
	}
	return _u
}

// AddGatewayAmount adds value to the "gateway_amount" field.
func (_u *PaymentRefundUpdate) AddGatewayAmount(v float64) *PaymentRefundUpdate {
	_u.mutation.AddGatewayAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentRefundUpdate) SetCurrency(v string) *PaymentRefundUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableCurrency(v *string) *PaymentRefundUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *PaymentRefundUpdate) SetReason(v string) *PaymentRefundUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableReason(v *string) *PaymentRefundUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *PaymentRefundUpdate) ClearReason() *PaymentRefundUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentRefundUpdate) SetStatus(v string) *PaymentRefundUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableStatus(v *string) *PaymentRefundUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProviderRefundID sets the "provider_refund_id" field.
func (_u *PaymentRefundUpdate) SetProviderRefundID(v string) *PaymentRefundUpdate {
	_u.mutation.SetProviderRefundID(v)
	return _u
}

// SetNillableProviderRefundID sets the "provider_refund_id" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableProviderRefundID(v *string) *PaymentRefundUpdate {
	if v != nil {
		_u.SetProviderRefundID(*v)
	}
	return _u
}

// SetOperator sets the "operator" field.
func (_u *PaymentRefundUpdate) SetOperator(v string) *PaymentRefundUpdate {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableOperator(v *string) *PaymentRefundUpdate {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// SetDeductionType sets the "deduction_type" field.
func (_u *PaymentRefundUpdate) SetDeductionType(v string) *PaymentRefundUpdate {
	_u.mutation.SetDeductionType(v)
	return _u
}

// SetNillableDeductionType sets the "deduction_type" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableDeductionType(v *string) *PaymentRefundUpdate {
	if v != nil {
		_u.SetDeductionType(*v)
	}
	return _u
}

// SetBalanceDeducted sets the "balance_deducted" field.
func (_u *PaymentRefundUpdate) SetBalanceDeducted(v float64) *PaymentRefundUpdate {
	_u.mutation.ResetBalanceDeducted()
	_u.mutation.SetBalanceDeducted(v)
	return _u
}

// SetNillableBalanceDeducted sets the "balance_deducted" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableBalanceDeducted(v *float64) *PaymentRefundUpdate {
	if v != nil {
		_u.SetBalanceDeducted(*v)
	}
	return _u
}

// AddBalanceDeducted adds value to the "balance_deducted" field.
func (_u *PaymentRefundUpdate) AddBalanceDeducted(v float64) *PaymentRefundUpdate {
	_u.mutation.AddBalanceDeducted(v)
	return _u
}

// SetSubDaysDeducted sets the "sub_days_deducted" field.
func (_u *PaymentRefundUpdate) SetSubDaysDeducted(v int) *PaymentRefundUpdate {
	_u.mutation.ResetSubDaysDeducted()
	_u.mutation.SetSubDaysDeducted(v)
	return _u
}

// SetNillableSubDaysDeducted sets the "sub_days_deducted" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableSubDaysDeducted(v *int) *PaymentRefundUpdate {
	if v != nil {
		_u.SetSubDaysDeducted(*v)
	}
	return _u
}

// AddSubDaysDeducted adds value to the "sub_days_deducted" field.
func (_u *PaymentRefundUpdate) AddSubDaysDeducted(v int) *PaymentRefundUpdate {
	_u.mutation.AddSubDaysDeducted(v)
	return _u
}

// SetDeductionRollbackOk sets the "deduction_rollback_ok" field.
func (_u *PaymentRefundUpdate) SetDeductionRollbackOk(v bool) *PaymentRefundUpdate {
	_u.mutation.SetDeductionRollbackOk(v)
	return _u
}

// SetNillableDeductionRollbackOk sets the "deduction_rollback_ok" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableDeductionRollbackOk(v *bool) *PaymentRefundUpdate {
	if v != nil {
		_u.SetDeductionRollbackOk(*v)
	}
	return _u
}

// SetForce sets the "force" field.
func (_u *PaymentRefundUpdate) SetForce(v bool) *PaymentRefundUpdate {
	_u.mutation.SetForce(v)
	return _u
}

// SetNillableForce sets the "force" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableForce(v *bool) *PaymentRefundUpdate {
	if v != nil {
		_u.SetForce(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *PaymentRefundUpdate) SetFailureReason(v string) *PaymentRefundUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableFailureReason(v *string) *PaymentRefundUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *PaymentRefundUpdate) ClearFailureReason() *PaymentRefundUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *PaymentRefundUpdate) SetCompletedAt(v time.Time) *PaymentRefundUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *PaymentRefundUpdate) SetNillableCompletedAt(v *time.Time) *PaymentRefundUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *PaymentRefundUpdate) ClearCompletedAt() *PaymentRefundUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentRefundUpdate) SetUpdatedAt(v time.Time) *PaymentRefundUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentRefundMutation object of the builder.
func (_u *PaymentRefundUpdate) Mutation() *PaymentRefundMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentRefundUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentRefundUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentRefundUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentRefundUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentRefundUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentrefund.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentRefundUpdate) check() error {
	if v, ok := _u.mutation.RefundNo(); ok {
		if err := paymentrefund.RefundNoValidator(v); err != nil {
			return &ValidationError{Name: "refund_no", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.refund_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentrefund.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentrefund.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderRefundID(); ok {
		if err := paymentrefund.ProviderRefundIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_refund_id", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.provider_refund_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operator(); ok {
		if err := paymentrefund.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.operator": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeductionType(); ok {
		if err := paymentrefund.DeductionTypeValidator(v); err != nil {
			return &ValidationError{Name: "deduction_type", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.deduction_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentRefundUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentrefund.Table, paymentrefund.Columns, sqlgraph.NewFieldSpec(paymentrefund.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(paymentrefund.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(paymentrefund.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundNo(); ok {
		_spec.SetField(paymentrefund.FieldRefundNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentrefund.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentrefund.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GatewayAmount(); ok {
		_spec.SetField(paymentrefund.FieldGatewayAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGatewayAmount(); ok {
		_spec.AddField(paymentrefund.FieldGatewayAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentrefund.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(paymentrefund.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(paymentrefund.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentrefund.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderRefundID(); ok {
		_spec.SetField(paymentrefund.FieldProviderRefundID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(paymentrefund.FieldOperator, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeductionType(); ok {
		_spec.SetField(paymentrefund.FieldDeductionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceDeducted(); ok {
		_spec.SetField(paymentrefund.FieldBalanceDeducted, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceDeducted(); ok {
		_spec.AddField(paymentrefund.FieldBalanceDeducted, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SubDaysDeducted(); ok {
		_spec.SetField(paymentrefund.FieldSubDaysDeducted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSubDaysDeducted(); ok {
		_spec.AddField(paymentrefund.FieldSubDaysDeducted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DeductionRollbackOk(); ok {
		_spec.SetField(paymentrefund.FieldDeductionRollbackOk, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Force(); ok {
		_spec.SetField(paymentrefund.FieldForce, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(paymentrefund.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(paymentrefund.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(paymentrefund.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(paymentrefund.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentrefund.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentrefund.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentRefundUpdateOne is the builder for updating a single PaymentRefund entity.
type PaymentRefundUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentRefundMutation
}

// SetOrderID sets the "order_id" field.
func (_u *PaymentRefundUpdateOne) SetOrderID(v int64) *PaymentRefundUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableOrderID(v *int64) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *PaymentRefundUpdateOne) AddOrderID(v int64) *PaymentRefundUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetRefundNo sets the "refund_no" field.
func (_u *PaymentRefundUpdateOne) SetRefundNo(v string) *PaymentRefundUpdateOne {
	_u.mutation.SetRefundNo(v)
	return _u
}

// SetNillableRefundNo sets the "refund_no" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableRefundNo(v *string) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetRefundNo(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentRefundUpdateOne) SetAmount(v float64) *PaymentRefundUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableAmount(v *float64) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentRefundUpdateOne) AddAmount(v float64) *PaymentRefundUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetGatewayAmount sets the "gateway_amount" field.
func (_u *PaymentRefundUpdateOne) SetGatewayAmount(v float64) *PaymentRefundUpdateOne {
	_u.mutation.ResetGatewayAmount()
	_u.mutation.SetGatewayAmount(v)
	return _u
}

// SetNillableGatewayAmount sets the "gateway_amount" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableGatewayAmount(v *float64) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetGatewayAmount(*v)
	}
	return _u
}

// AddGatewayAmount adds value to the "gateway_amount" field.
func (_u *PaymentRefundUpdateOne) AddGatewayAmount(v float64) *PaymentRefundUpdateOne {
	_u.mutation.AddGatewayAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentRefundUpdateOne) SetCurrency(v string) *PaymentRefundUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableCurrency(v *string) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *PaymentRefundUpdateOne) SetReason(v string) *PaymentRefundUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableReason(v *string) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *PaymentRefundUpdateOne) ClearReason() *PaymentRefundUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentRefundUpdateOne) SetStatus(v string) *PaymentRefundUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableStatus(v *string) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProviderRefundID sets the "provider_refund_id" field.
func (_u *PaymentRefundUpdateOne) SetProviderRefundID(v string) *PaymentRefundUpdateOne {
	_u.mutation.SetProviderRefundID(v)
	return _u
}

// SetNillableProviderRefundID sets the "provider_refund_id" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableProviderRefundID(v *string) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetProviderRefundID(*v)
	}
	return _u
}

// SetOperator sets the "operator" field.
func (_u *PaymentRefundUpdateOne) SetOperator(v string) *PaymentRefundUpdateOne {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableOperator(v *string) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// SetDeductionType sets the "deduction_type" field.
func (_u *PaymentRefundUpdateOne) SetDeductionType(v string) *PaymentRefundUpdateOne {
	_u.mutation.SetDeductionType(v)
	return _u
}

// SetNillableDeductionType sets the "deduction_type" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableDeductionType(v *string) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetDeductionType(*v)
	}
	return _u
}

// SetBalanceDeducted sets the "balance_deducted" field.
func (_u *PaymentRefundUpdateOne) SetBalanceDeducted(v float64) *PaymentRefundUpdateOne {
	_u.mutation.ResetBalanceDeducted()
	_u.mutation.SetBalanceDeducted(v)
	return _u
}

// SetNillableBalanceDeducted sets the "balance_deducted" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableBalanceDeducted(v *float64) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetBalanceDeducted(*v)
	}
	return _u
}

// AddBalanceDeducted adds value to the "balance_deducted" field.
func (_u *PaymentRefundUpdateOne) AddBalanceDeducted(v float64) *PaymentRefundUpdateOne {
	_u.mutation.AddBalanceDeducted(v)
	return _u
}

// SetSubDaysDeducted sets the "sub_days_deducted" field.
func (_u *PaymentRefundUpdateOne) SetSubDaysDeducted(v int) *PaymentRefundUpdateOne {
	_u.mutation.ResetSubDaysDeducted()
	_u.mutation.SetSubDaysDeducted(v)
	return _u
}

// SetNillableSubDaysDeducted sets the "sub_days_deducted" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableSubDaysDeducted(v *int) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetSubDaysDeducted(*v)
	}
	return _u
}

// AddSubDaysDeducted adds value to the "sub_days_deducted" field.
func (_u *PaymentRefundUpdateOne) AddSubDaysDeducted(v int) *PaymentRefundUpdateOne {
	_u.mutation.AddSubDaysDeducted(v)
	return _u
}

// SetDeductionRollbackOk sets the "deduction_rollback_ok" field.
func (_u *PaymentRefundUpdateOne) SetDeductionRollbackOk(v bool) *PaymentRefundUpdateOne {
	_u.mutation.SetDeductionRollbackOk(v)
	return _u
}

// SetNillableDeductionRollbackOk sets the "deduction_rollback_ok" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableDeductionRollbackOk(v *bool) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetDeductionRollbackOk(*v)
	}
	return _u
}

// SetForce sets the "force" field.
func (_u *PaymentRefundUpdateOne) SetForce(v bool) *PaymentRefundUpdateOne {
	_u.mutation.SetForce(v)
	return _u
}

// SetNillableForce sets the "force" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableForce(v *bool) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetForce(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *PaymentRefundUpdateOne) SetFailureReason(v string) *PaymentRefundUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableFailureReason(v *string) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *PaymentRefundUpdateOne) ClearFailureReason() *PaymentRefundUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *PaymentRefundUpdateOne) SetCompletedAt(v time.Time) *PaymentRefundUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *PaymentRefundUpdateOne) SetNillableCompletedAt(v *time.Time) *PaymentRefundUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *PaymentRefundUpdateOne) ClearCompletedAt() *PaymentRefundUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentRefundUpdateOne) SetUpdatedAt(v time.Time) *PaymentRefundUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentRefundMutation object of the builder.
func (_u *PaymentRefundUpdateOne) Mutation() *PaymentRefundMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentRefundUpdate builder.
func (_u *PaymentRefundUpdateOne) Where(ps ...predicate.PaymentRefund) *PaymentRefundUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentRefundUpdateOne) Select(field string, fields ...string) *PaymentRefundUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentRefund entity.
func (_u *PaymentRefundUpdateOne) Save(ctx context.Context) (*PaymentRefund, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentRefundUpdateOne) SaveX(ctx context.Context) *PaymentRefund {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentRefundUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentRefundUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentRefundUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentrefund.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentRefundUpdateOne) check() error {
	if v, ok := _u.mutation.RefundNo(); ok {
		if err := paymentrefund.RefundNoValidator(v); err != nil {
			return &ValidationError{Name: "refund_no", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.refund_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentrefund.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentrefund.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderRefundID(); ok {
		if err := paymentrefund.ProviderRefundIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_refund_id", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.provider_refund_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operator(); ok {
		if err := paymentrefund.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.operator": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeductionType(); ok {
		if err := paymentrefund.DeductionTypeValidator(v); err != nil {
			return &ValidationError{Name: "deduction_type", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.deduction_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentRefundUpdateOne) sqlSave(ctx context.Context) (_node *PaymentRefund, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentrefund.Table, paymentrefund.Columns, sqlgraph.NewFieldSpec(paymentrefund.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentRefund.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentrefund.FieldID)
		for _, f := range fields {
			if !paymentrefund.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentrefund.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(paymentrefund.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(paymentrefund.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundNo(); ok {
		_spec.SetField(paymentrefund.FieldRefundNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentrefund.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentrefund.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GatewayAmount(); ok {
		_spec.SetField(paymentrefund.FieldGatewayAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGatewayAmount(); ok {
		_spec.AddField(paymentrefund.FieldGatewayAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentrefund.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(paymentrefund.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(paymentrefund.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentrefund.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderRefundID(); ok {
		_spec.SetField(paymentrefund.FieldProviderRefundID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(paymentrefund.FieldOperator, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeductionType(); ok {
		_spec.SetField(paymentrefund.FieldDeductionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceDeducted(); ok {
		_spec.SetField(paymentrefund.FieldBalanceDeducted, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceDeducted(); ok {
		_spec.AddField(paymentrefund.FieldBalanceDeducted, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SubDaysDeducted(); ok {
		_spec.SetField(paymentrefund.FieldSubDaysDeducted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSubDaysDeducted(); ok {
		_spec.AddField(paymentrefund.FieldSubDaysDeducted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DeductionRollbackOk(); ok {
		_spec.SetField(paymentrefund.FieldDeductionRollbackOk, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Force(); ok {
		_spec.SetField(paymentrefund.FieldForce, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(paymentrefund.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(paymentrefund.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(paymentrefund.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(paymentrefund.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentrefund.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PaymentRefund{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentrefund.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
