// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentrefund"
)

// PaymentRefundCreate is the builder for creating a PaymentRefund entity.
type PaymentRefundCreate struct {
	config
	mutation *PaymentRefundMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrderID sets the "order_id" field.
func (_c *PaymentRefundCreate) SetOrderID(v int64) *PaymentRefundCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetRefundNo sets the "refund_no" field.
func (_c *PaymentRefundCreate) SetRefundNo(v string) *PaymentRefundCreate {
	_c.mutation.SetRefundNo(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *PaymentRefundCreate) SetAmount(v float64) *PaymentRefundCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetGatewayAmount sets the "gateway_amount" field.
func (_c *PaymentRefundCreate) SetGatewayAmount(v float64) *PaymentRefundCreate {
	_c.mutation.SetGatewayAmount(v)
	return _c
}

// SetNillableGatewayAmount sets the "gateway_amount" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableGatewayAmount(v *float64) *PaymentRefundCreate {
	if v != nil {
		_c.SetGatewayAmount(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PaymentRefundCreate) SetCurrency(v string) *PaymentRefundCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableCurrency(v *string) *PaymentRefundCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *PaymentRefundCreate) SetReason(v string) *PaymentRefundCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableReason(v *string) *PaymentRefundCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentRefundCreate) SetStatus(v string) *PaymentRefundCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableStatus(v *string) *PaymentRefundCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProviderRefundID sets the "provider_refund_id" field.
func (_c *PaymentRefundCreate) SetProviderRefundID(v string) *PaymentRefundCreate {
	_c.mutation.SetProviderRefundID(v)
	return _c
}

// SetNillableProviderRefundID sets the "provider_refund_id" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableProviderRefundID(v *string) *PaymentRefundCreate {
	if v != nil {
		_c.SetProviderRefundID(*v)
	}
	return _c
}

// SetOperator sets the "operator" field.
func (_c *PaymentRefundCreate) SetOperator(v string) *PaymentRefundCreate {
	_c.mutation.SetOperator(v)
	return _c
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableOperator(v *string) *PaymentRefundCreate {
	if v != nil {
		_c.SetOperator(*v)
	}
	return _c
}

// SetDeductionType sets the "deduction_type" field.
func (_c *PaymentRefundCreate) SetDeductionType(v string) *PaymentRefundCreate {
	_c.mutation.SetDeductionType(v)
	return _c
}

// SetNillableDeductionType sets the "deduction_type" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableDeductionType(v *string) *PaymentRefundCreate {
	if v != nil {
		_c.SetDeductionType(*v)
	}
	return _c
}

// SetBalanceDeducted sets the "balance_deducted" field.
func (_c *PaymentRefundCreate) SetBalanceDeducted(v float64) *PaymentRefundCreate {
	_c.mutation.SetBalanceDeducted(v)
	return _c
}

// SetNillableBalanceDeducted sets the "balance_deducted" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableBalanceDeducted(v *float64) *PaymentRefundCreate {
	if v != nil {
		_c.SetBalanceDeducted(*v)
	}
	return _c
}

// SetSubDaysDeducted sets the "sub_days_deducted" field.
func (_c *PaymentRefundCreate) SetSubDaysDeducted(v int) *PaymentRefundCreate {
	_c.mutation.SetSubDaysDeducted(v)
	return _c
}

// SetNillableSubDaysDeducted sets the "sub_days_deducted" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableSubDaysDeducted(v *int) *PaymentRefundCreate {
	if v != nil {
		_c.SetSubDaysDeducted(*v)
	}
	return _c
}

// SetDeductionRollbackOk sets the "deduction_rollback_ok" field.
func (_c *PaymentRefundCreate) SetDeductionRollbackOk(v bool) *PaymentRefundCreate {
	_c.mutation.SetDeductionRollbackOk(v)
	return _c
}

// SetNillableDeductionRollbackOk sets the "deduction_rollback_ok" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableDeductionRollbackOk(v *bool) *PaymentRefundCreate {
	if v != nil {
		_c.SetDeductionRollbackOk(*v)
	}
	return _c
}

// SetForce sets the "force" field.
func (_c *PaymentRefundCreate) SetForce(v bool) *PaymentRefundCreate {
	_c.mutation.SetForce(v)
	return _c
}

// SetNillableForce sets the "force" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableForce(v *bool) *PaymentRefundCreate {
	if v != nil {
		_c.SetForce(*v)
	}
	return _c
}

// SetFailureReason sets the "failure_reason" field.
func (_c *PaymentRefundCreate) SetFailureReason(v string) *PaymentRefundCreate {
	_c.mutation.SetFailureReason(v)
	return _c
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableFailureReason(v *string) *PaymentRefundCreate {
	if v != nil {
		_c.SetFailureReason(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *PaymentRefundCreate) SetCompletedAt(v time.Time) *PaymentRefundCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableCompletedAt(v *time.Time) *PaymentRefundCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentRefundCreate) SetCreatedAt(v time.Time) *PaymentRefundCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableCreatedAt(v *time.Time) *PaymentRefundCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentRefundCreate) SetUpdatedAt(v time.Time) *PaymentRefundCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentRefundCreate) SetNillableUpdatedAt(v *time.Time) *PaymentRefundCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PaymentRefundMutation object of the builder.
func (_c *PaymentRefundCreate) Mutation() *PaymentRefundMutation {
	return _c.mutation
}

// Save creates the PaymentRefund in the database.
func (_c *PaymentRefundCreate) Save(ctx context.Context) (*PaymentRefund, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentRefundCreate) SaveX(ctx context.Context) *PaymentRefund {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentRefundCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentRefundCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentRefundCreate) defaults() {
	if _, ok := _c.mutation.GatewayAmount(); !ok {
		v := paymentrefund.DefaultGatewayAmount
		_c.mutation.SetGatewayAmount(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := paymentrefund.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentrefund.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ProviderRefundID(); !ok {
		v := paymentrefund.DefaultProviderRefundID
		_c.mutation.SetProviderRefundID(v)
	}
	if _, ok := _c.mutation.Operator(); !ok {
		v := paymentrefund.DefaultOperator
		_c.mutation.SetOperator(v)
	}
	if _, ok := _c.mutation.DeductionType(); !ok {
		v := paymentrefund.DefaultDeductionType
		_c.mutation.SetDeductionType(v)
	}
	if _, ok := _c.mutation.BalanceDeducted(); !ok {
		v := paymentrefund.DefaultBalanceDeducted
		_c.mutation.SetBalanceDeducted(v)
	}
	if _, ok := _c.mutation.SubDaysDeducted(); !ok {
		v := paymentrefund.DefaultSubDaysDeducted
		_c.mutation.SetSubDaysDeducted(v)
	}
	if _, ok := _c.mutation.DeductionRollbackOk(); !ok {
		v := paymentrefund.DefaultDeductionRollbackOk
		_c.mutation.SetDeductionRollbackOk(v)
	}
	if _, ok := _c.mutation.Force(); !ok {
		v := paymentrefund.DefaultForce
		_c.mutation.SetForce(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentrefund.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentrefund.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentRefundCreate) check() error {
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "PaymentRefund.order_id"`)}
	}
	if _, ok := _c.mutation.RefundNo(); !ok {
		return &ValidationError{Name: "refund_no", err: errors.New(`ent: missing required field "PaymentRefund.refund_no"`)}
	}
	if v, ok := _c.mutation.RefundNo(); ok {
		if err := paymentrefund.RefundNoValidator(v); err != nil {
			return &ValidationError{Name: "refund_no", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.refund_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "PaymentRefund.amount"`)}
	}
	if _, ok := _c.mutation.GatewayAmount(); !ok {
		return &ValidationError{Name: "gateway_amount", err: errors.New(`ent: missing required field "PaymentRefund.gateway_amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "PaymentRefund.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := paymentrefund.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentRefund.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentrefund.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderRefundID(); !ok {
		return &ValidationError{Name: "provider_refund_id", err: errors.New(`ent: missing required field "PaymentRefund.provider_refund_id"`)}
	}
	if v, ok := _c.mutation.ProviderRefundID(); ok {
		if err := paymentrefund.ProviderRefundIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_refund_id", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.provider_refund_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Operator(); !ok {
		return &ValidationError{Name: "operator", err: errors.New(`ent: missing required field "PaymentRefund.operator"`)}
	}
	if v, ok := _c.mutation.Operator(); ok {
		if err := paymentrefund.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.operator": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeductionType(); !ok {
		return &ValidationError{Name: "deduction_type", err: errors.New(`ent: missing required field "PaymentRefund.deduction_type"`)}
	}
	if v, ok := _c.mutation.DeductionType(); ok {
		if err := paymentrefund.DeductionTypeValidator(v); err != nil {
			return &ValidationError{Name: "deduction_type", err: fmt.Errorf(`ent: validator failed for field "PaymentRefund.deduction_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceDeducted(); !ok {
		return &ValidationError{Name: "balance_deducted", err: errors.New(`ent: missing required field "PaymentRefund.balance_deducted"`)}
	}
	if _, ok := _c.mutation.SubDaysDeducted(); !ok {
		return &ValidationError{Name: "sub_days_deducted", err: errors.New(`ent: missing required field "PaymentRefund.sub_days_deducted"`)}
	}
	if _, ok := _c.mutation.DeductionRollbackOk(); !ok {
		return &ValidationError{Name: "deduction_rollback_ok", err: errors.New(`ent: missing required field "PaymentRefund.deduction_rollback_ok"`)}
	}
	if _, ok := _c.mutation.Force(); !ok {
		return &ValidationError{Name: "force", err: errors.New(`ent: missing required field "PaymentRefund.force"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentRefund.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentRefund.updated_at"`)}
	}
	return nil
}

func (_c *PaymentRefundCreate) sqlSave(ctx context.Context) (*PaymentRefund, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentRefundCreate) createSpec() (*PaymentRefund, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentRefund{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentrefund.Table, sqlgraph.NewFieldSpec(paymentrefund.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(paymentrefund.FieldOrderID, field.TypeInt64, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.RefundNo(); ok {
		_spec.SetField(paymentrefund.FieldRefundNo, field.TypeString, value)
		_node.RefundNo = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(paymentrefund.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.GatewayAmount(); ok {
		_spec.SetField(paymentrefund.FieldGatewayAmount, field.TypeFloat64, value)
		_node.GatewayAmount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(paymentrefund.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(paymentrefund.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentrefund.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProviderRefundID(); ok {
		_spec.SetField(paymentrefund.FieldProviderRefundID, field.TypeString, value)
		_node.ProviderRefundID = value
	}
	if value, ok := _c.mutation.Operator(); ok {
		_spec.SetField(paymentrefund.FieldOperator, field.TypeString, value)
		_node.Operator = value
	}
	if value, ok := _c.mutation.DeductionType(); ok {
		_spec.SetField(paymentrefund.FieldDeductionType, field.TypeString, value)
		_node.DeductionType = value
	}
	if value, ok := _c.mutation.BalanceDeducted(); ok {
		_spec.SetField(paymentrefund.FieldBalanceDeducted, field.TypeFloat64, value)
		_node.BalanceDeducted = value
	}
	if value, ok := _c.mutation.SubDaysDeducted(); ok {
		_spec.SetField(paymentrefund.FieldSubDaysDeducted, field.TypeInt, value)
		_node.SubDaysDeducted = value
	}
	if value, ok := _c.mutation.DeductionRollbackOk(); ok {
		_spec.SetField(paymentrefund.FieldDeductionRollbackOk, field.TypeBool, value)
		_node.DeductionRollbackOk = value
	}
	if value, ok := _c.mutation.Force(); ok {
		_spec.SetField(paymentrefund.FieldForce, field.TypeBool, value)
		_node.Force = value
	}
	if value, ok := _c.mutation.FailureReason(); ok {
		_spec.SetField(paymentrefund.FieldFailureReason, field.TypeString, value)
		_node.FailureReason = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(paymentrefund.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentrefund.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentrefund.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentRefund.Create().
//		SetOrderID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentRefundUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentRefundCreate) OnConflict(opts ...sql.ConflictOption) *PaymentRefundUpsertOne {
	_c.conflict = opts
	return &PaymentRefundUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentRefund.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentRefundCreate) OnConflictColumns(columns ...string) *PaymentRefundUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentRefundUpsertOne{
		create: _c,
	}
}

type (
	// PaymentRefundUpsertOne is the builder for "upsert"-ing
	//  one PaymentRefund node.
	PaymentRefundUpsertOne struct {
		create *PaymentRefundCreate
	}

	// PaymentRefundUpsert is the "OnConflict" setter.
	PaymentRefundUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrderID sets the "order_id" field.
func (u *PaymentRefundUpsert) SetOrderID(v int64) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateOrderID() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldOrderID)
	return u
}

// AddOrderID adds v to the "order_id" field.
func (u *PaymentRefundUpsert) AddOrderID(v int64) *PaymentRefundUpsert {
	u.Add(paymentrefund.FieldOrderID, v)
	return u
}

// SetRefundNo sets the "refund_no" field.
func (u *PaymentRefundUpsert) SetRefundNo(v string) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldRefundNo, v)
	return u
}

// UpdateRefundNo sets the "refund_no" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateRefundNo() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldRefundNo)
	return u
}

// SetAmount sets the "amount" field.
func (u *PaymentRefundUpsert) SetAmount(v float64) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateAmount() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *PaymentRefundUpsert) AddAmount(v float64) *PaymentRefundUpsert {
	u.Add(paymentrefund.FieldAmount, v)
	return u
}

// SetGatewayAmount sets the "gateway_amount" field.
func (u *PaymentRefundUpsert) SetGatewayAmount(v float64) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldGatewayAmount, v)
	return u
}

// UpdateGatewayAmount sets the "gateway_amount" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateGatewayAmount() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldGatewayAmount)
	return u
}

// AddGatewayAmount adds v to the "gateway_amount" field.
func (u *PaymentRefundUpsert) AddGatewayAmount(v float64) *PaymentRefundUpsert {
	u.Add(paymentrefund.FieldGatewayAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *PaymentRefundUpsert) SetCurrency(v string) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateCurrency() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldCurrency)
	return u
}

// SetReason sets the "reason" field.
func (u *PaymentRefundUpsert) SetReason(v string) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateReason() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *PaymentRefundUpsert) ClearReason() *PaymentRefundUpsert {
	u.SetNull(paymentrefund.FieldReason)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentRefundUpsert) SetStatus(v string) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateStatus() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldStatus)
	return u
}

// SetProviderRefundID sets the "provider_refund_id" field.
func (u *PaymentRefundUpsert) SetProviderRefundID(v string) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldProviderRefundID, v)
	return u
}

// UpdateProviderRefundID sets the "provider_refund_id" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateProviderRefundID() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldProviderRefundID)
	return u
}

// SetOperator sets the "operator" field.
func (u *PaymentRefundUpsert) SetOperator(v string) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldOperator, v)
	return u
}

// UpdateOperator sets the "operator" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateOperator() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldOperator)
	return u
}

// SetDeductionType sets the "deduction_type" field.
func (u *PaymentRefundUpsert) SetDeductionType(v string) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldDeductionType, v)
	return u
}

// UpdateDeductionType sets the "deduction_type" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateDeductionType() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldDeductionType)
	return u
}

// SetBalanceDeducted sets the "balance_deducted" field.
func (u *PaymentRefundUpsert) SetBalanceDeducted(v float64) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldBalanceDeducted, v)
	return u
}

// UpdateBalanceDeducted sets the "balance_deducted" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateBalanceDeducted() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldBalanceDeducted)
	return u
}

// AddBalanceDeducted adds v to the "balance_deducted" field.
func (u *PaymentRefundUpsert) AddBalanceDeducted(v float64) *PaymentRefundUpsert {
	u.Add(paymentrefund.FieldBalanceDeducted, v)
	return u
}

// SetSubDaysDeducted sets the "sub_days_deducted" field.
func (u *PaymentRefundUpsert) SetSubDaysDeducted(v int) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldSubDaysDeducted, v)
	return u
}

// UpdateSubDaysDeducted sets the "sub_days_deducted" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateSubDaysDeducted() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldSubDaysDeducted)
	return u
}

// AddSubDaysDeducted adds v to the "sub_days_deducted" field.
func (u *PaymentRefundUpsert) AddSubDaysDeducted(v int) *PaymentRefundUpsert {
	u.Add(paymentrefund.FieldSubDaysDeducted, v)
	return u
}

// SetDeductionRollbackOk sets the "deduction_rollback_ok" field.
func (u *PaymentRefundUpsert) SetDeductionRollbackOk(v bool) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldDeductionRollbackOk, v)
	return u
}

// UpdateDeductionRollbackOk sets the "deduction_rollback_ok" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateDeductionRollbackOk() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldDeductionRollbackOk)
	return u
}

// SetForce sets the "force" field.
func (u *PaymentRefundUpsert) SetForce(v bool) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldForce, v)
	return u
}

// UpdateForce sets the "force" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateForce() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldForce)
	return u
}

// SetFailureReason sets the "failure_reason" field.
func (u *PaymentRefundUpsert) SetFailureReason(v string) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldFailureReason, v)
	return u
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateFailureReason() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldFailureReason)
	return u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (u *PaymentRefundUpsert) ClearFailureReason() *PaymentRefundUpsert {
	u.SetNull(paymentrefund.FieldFailureReason)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *PaymentRefundUpsert) SetCompletedAt(v time.Time) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateCompletedAt() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *PaymentRefundUpsert) ClearCompletedAt() *PaymentRefundUpsert {
	u.SetNull(paymentrefund.FieldCompletedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentRefundUpsert) SetUpdatedAt(v time.Time) *PaymentRefundUpsert {
	u.Set(paymentrefund.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentRefundUpsert) UpdateUpdatedAt() *PaymentRefundUpsert {
	u.SetExcluded(paymentrefund.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentRefund.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentRefundUpsertOne) UpdateNewValues() *PaymentRefundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentrefund.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentRefund.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentRefundUpsertOne) Ignore() *PaymentRefundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentRefundUpsertOne) DoNothing() *PaymentRefundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentRefundCreate.OnConflict
// documentation for more info.
func (u *PaymentRefundUpsertOne) Update(set func(*PaymentRefundUpsert)) *PaymentRefundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentRefundUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *PaymentRefundUpsertOne) SetOrderID(v int64) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *PaymentRefundUpsertOne) AddOrderID(v int64) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateOrderID() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateOrderID()
	})
}

// SetRefundNo sets the "refund_no" field.
func (u *PaymentRefundUpsertOne) SetRefundNo(v string) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetRefundNo(v)
	})
}

// UpdateRefundNo sets the "refund_no" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateRefundNo() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateRefundNo()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentRefundUpsertOne) SetAmount(v float64) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentRefundUpsertOne) AddAmount(v float64) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateAmount() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateAmount()
	})
}

// SetGatewayAmount sets the "gateway_amount" field.
func (u *PaymentRefundUpsertOne) SetGatewayAmount(v float64) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetGatewayAmount(v)
	})
}

// AddGatewayAmount adds v to the "gateway_amount" field.
func (u *PaymentRefundUpsertOne) AddGatewayAmount(v float64) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.AddGatewayAmount(v)
	})
}

// UpdateGatewayAmount sets the "gateway_amount" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateGatewayAmount() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateGatewayAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentRefundUpsertOne) SetCurrency(v string) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateCurrency() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateCurrency()
	})
}

// SetReason sets the "reason" field.
func (u *PaymentRefundUpsertOne) SetReason(v string) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateReason() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *PaymentRefundUpsertOne) ClearReason() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.ClearReason()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentRefundUpsertOne) SetStatus(v string) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateStatus() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateStatus()
	})
}

// SetProviderRefundID sets the "provider_refund_id" field.
func (u *PaymentRefundUpsertOne) SetProviderRefundID(v string) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetProviderRefundID(v)
	})
}

// UpdateProviderRefundID sets the "provider_refund_id" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateProviderRefundID() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateProviderRefundID()
	})
}

// SetOperator sets the "operator" field.
func (u *PaymentRefundUpsertOne) SetOperator(v string) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetOperator(v)
	})
}

// UpdateOperator sets the "operator" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateOperator() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateOperator()
	})
}

// SetDeductionType sets the "deduction_type" field.
func (u *PaymentRefundUpsertOne) SetDeductionType(v string) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetDeductionType(v)
	})
}

// UpdateDeductionType sets the "deduction_type" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateDeductionType() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateDeductionType()
	})
}

// SetBalanceDeducted sets the "balance_deducted" field.
func (u *PaymentRefundUpsertOne) SetBalanceDeducted(v float64) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetBalanceDeducted(v)
	})
}

// AddBalanceDeducted adds v to the "balance_deducted" field.
func (u *PaymentRefundUpsertOne) AddBalanceDeducted(v float64) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.AddBalanceDeducted(v)
	})
}

// UpdateBalanceDeducted sets the "balance_deducted" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateBalanceDeducted() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateBalanceDeducted()
	})
}

// SetSubDaysDeducted sets the "sub_days_deducted" field.
func (u *PaymentRefundUpsertOne) SetSubDaysDeducted(v int) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetSubDaysDeducted(v)
	})
}

// AddSubDaysDeducted adds v to the "sub_days_deducted" field.
func (u *PaymentRefundUpsertOne) AddSubDaysDeducted(v int) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.AddSubDaysDeducted(v)
	})
}

// UpdateSubDaysDeducted sets the "sub_days_deducted" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateSubDaysDeducted() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateSubDaysDeducted()
	})
}

// SetDeductionRollbackOk sets the "deduction_rollback_ok" field.
func (u *PaymentRefundUpsertOne) SetDeductionRollbackOk(v bool) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetDeductionRollbackOk(v)
	})
}

// UpdateDeductionRollbackOk sets the "deduction_rollback_ok" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateDeductionRollbackOk() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateDeductionRollbackOk()
	})
}

// SetForce sets the "force" field.
func (u *PaymentRefundUpsertOne) SetForce(v bool) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetForce(v)
	})
}

// UpdateForce sets the "force" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateForce() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateForce()
	})
}

// SetFailureReason sets the "failure_reason" field.
func (u *PaymentRefundUpsertOne) SetFailureReason(v string) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetFailureReason(v)
	})
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateFailureReason() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateFailureReason()
	})
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (u *PaymentRefundUpsertOne) ClearFailureReason() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.ClearFailureReason()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *PaymentRefundUpsertOne) SetCompletedAt(v time.Time) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateCompletedAt() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *PaymentRefundUpsertOne) ClearCompletedAt() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentRefundUpsertOne) SetUpdatedAt(v time.Time) *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentRefundUpsertOne) UpdateUpdatedAt() *PaymentRefundUpsertOne {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentRefundUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentRefundCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentRefundUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentRefundUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentRefundUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentRefundCreateBulk is the builder for creating many PaymentRefund entities in bulk.
type PaymentRefundCreateBulk struct {
	config
	err      error
	builders []*PaymentRefundCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentRefund entities in the database.
func (_c *PaymentRefundCreateBulk) Save(ctx context.Context) ([]*PaymentRefund, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentRefund, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentRefundMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentRefundCreateBulk) SaveX(ctx context.Context) []*PaymentRefund {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentRefundCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentRefundCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentRefund.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentRefundUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentRefundCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentRefundUpsertBulk {
	_c.conflict = opts
	return &PaymentRefundUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentRefund.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentRefundCreateBulk) OnConflictColumns(columns ...string) *PaymentRefundUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentRefundUpsertBulk{
		create: _c,
	}
}

// PaymentRefundUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentRefund nodes.
type PaymentRefundUpsertBulk struct {
	create *PaymentRefundCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentRefund.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentRefundUpsertBulk) UpdateNewValues() *PaymentRefundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentrefund.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentRefund.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentRefundUpsertBulk) Ignore() *PaymentRefundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentRefundUpsertBulk) DoNothing() *PaymentRefundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentRefundCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentRefundUpsertBulk) Update(set func(*PaymentRefundUpsert)) *PaymentRefundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentRefundUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *PaymentRefundUpsertBulk) SetOrderID(v int64) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *PaymentRefundUpsertBulk) AddOrderID(v int64) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateOrderID() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateOrderID()
	})
}

// SetRefundNo sets the "refund_no" field.
func (u *PaymentRefundUpsertBulk) SetRefundNo(v string) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetRefundNo(v)
	})
}

// UpdateRefundNo sets the "refund_no" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateRefundNo() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateRefundNo()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentRefundUpsertBulk) SetAmount(v float64) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentRefundUpsertBulk) AddAmount(v float64) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateAmount() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateAmount()
	})
}

// SetGatewayAmount sets the "gateway_amount" field.
func (u *PaymentRefundUpsertBulk) SetGatewayAmount(v float64) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetGatewayAmount(v)
	})
}

// AddGatewayAmount adds v to the "gateway_amount" field.
func (u *PaymentRefundUpsertBulk) AddGatewayAmount(v float64) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.AddGatewayAmount(v)
	})
}

// UpdateGatewayAmount sets the "gateway_amount" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateGatewayAmount() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateGatewayAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentRefundUpsertBulk) SetCurrency(v string) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateCurrency() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateCurrency()
	})
}

// SetReason sets the "reason" field.
func (u *PaymentRefundUpsertBulk) SetReason(v string) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateReason() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *PaymentRefundUpsertBulk) ClearReason() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.ClearReason()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentRefundUpsertBulk) SetStatus(v string) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateStatus() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateStatus()
	})
}

// SetProviderRefundID sets the "provider_refund_id" field.
func (u *PaymentRefundUpsertBulk) SetProviderRefundID(v string) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetProviderRefundID(v)
	})
}

// UpdateProviderRefundID sets the "provider_refund_id" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateProviderRefundID() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateProviderRefundID()
	})
}

// SetOperator sets the "operator" field.
func (u *PaymentRefundUpsertBulk) SetOperator(v string) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetOperator(v)
	})
}

// UpdateOperator sets the "operator" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateOperator() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateOperator()
	})
}

// SetDeductionType sets the "deduction_type" field.
func (u *PaymentRefundUpsertBulk) SetDeductionType(v string) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetDeductionType(v)
	})
}

// UpdateDeductionType sets the "deduction_type" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateDeductionType() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateDeductionType()
	})
}

// SetBalanceDeducted sets the "balance_deducted" field.
func (u *PaymentRefundUpsertBulk) SetBalanceDeducted(v float64) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetBalanceDeducted(v)
	})
}

// AddBalanceDeducted adds v to the "balance_deducted" field.
func (u *PaymentRefundUpsertBulk) AddBalanceDeducted(v float64) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.AddBalanceDeducted(v)
	})
}

// UpdateBalanceDeducted sets the "balance_deducted" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateBalanceDeducted() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateBalanceDeducted()
	})
}

// SetSubDaysDeducted sets the "sub_days_deducted" field.
func (u *PaymentRefundUpsertBulk) SetSubDaysDeducted(v int) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetSubDaysDeducted(v)
	})
}

// AddSubDaysDeducted adds v to the "sub_days_deducted" field.
func (u *PaymentRefundUpsertBulk) AddSubDaysDeducted(v int) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.AddSubDaysDeducted(v)
	})
}

// UpdateSubDaysDeducted sets the "sub_days_deducted" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateSubDaysDeducted() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateSubDaysDeducted()
	})
}

// SetDeductionRollbackOk sets the "deduction_rollback_ok" field.
func (u *PaymentRefundUpsertBulk) SetDeductionRollbackOk(v bool) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetDeductionRollbackOk(v)
	})
}

// UpdateDeductionRollbackOk sets the "deduction_rollback_ok" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateDeductionRollbackOk() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateDeductionRollbackOk()
	})
}

// SetForce sets the "force" field.
func (u *PaymentRefundUpsertBulk) SetForce(v bool) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetForce(v)
	})
}

// UpdateForce sets the "force" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateForce() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateForce()
	})
}

// SetFailureReason sets the "failure_reason" field.
func (u *PaymentRefundUpsertBulk) SetFailureReason(v string) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetFailureReason(v)
	})
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateFailureReason() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateFailureReason()
	})
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (u *PaymentRefundUpsertBulk) ClearFailureReason() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.ClearFailureReason()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *PaymentRefundUpsertBulk) SetCompletedAt(v time.Time) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateCompletedAt() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *PaymentRefundUpsertBulk) ClearCompletedAt() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentRefundUpsertBulk) SetUpdatedAt(v time.Time) *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentRefundUpsertBulk) UpdateUpdatedAt() *PaymentRefundUpsertBulk {
	return u.Update(func(s *PaymentRefundUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentRefundUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentRefundCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentRefundCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentRefundUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
